// Generated by CoffeeScript 1.4.0

Ext.Loader.setConfig({
  enabled: true,
  paths: {
    "sacec": "app",
    "Overrides": 'overrides'
  }
});

Ext.syncRequire(["Ext.Component", "Ext.ComponentManager", "Ext.ComponentQuery"]);
